// Robert Moses Atlas — data
// Every event carries a year, a place and a source link. Where a date is a
// range or is uncertain, the label says so and `t` is the first firm year.
// Types: parkway, expressway, bridge, park, housing, culture, power, office, cost, unbuilt

window.ATLAS = {
  range: [1924, 1969],

  offices: [
    { name: 'President, Long Island State Park Commission', from: 1924, to: 1963 },
    { name: 'Chairman, New York State Council of Parks', from: 1924, to: 1963 },
    { name: 'New York Secretary of State', from: 1927, to: 1929 },
    { name: 'President, Jones Beach State Parkway Authority', from: 1933, to: 1963 },
    { name: 'President, Bethpage State Park Authority', from: 1933, to: 1963 },
    { name: 'New York City Parks Commissioner', from: 1934, to: 1960 },
    { name: 'Triborough Bridge (and Tunnel) Authority — member, then chairman', from: 1934, to: 1968 },
    { name: 'Member, City Planning Commission', from: 1942, to: 1960 },
    { name: 'City Construction Coordinator', from: 1946, to: 1960 },
    { name: 'Chairman, Mayor’s Committee on Slum Clearance', from: 1949, to: 1960 },
    { name: 'Chairman, New York State Power Authority', from: 1954, to: 1962 },
    { name: 'President, 1964 World’s Fair Corporation', from: 1960, to: 1966 },
  ],

  chapters: [
    {
      n: 1, from: 1924, to: 1930, title: 'Sand, parkways and a beach',
      text: 'A young reformer with no office of consequence writes himself one. Governor Al Smith signs the 1924 act creating the Long Island State Park Commission, and Moses, its president, uses its power to appropriate land to take estates and farmland for parks and the roads to reach them. By 1929 the Southern State Parkway is open, the Wantagh causeway crosses the bay, and Jones Beach, a barrier island raised fourteen feet with dredged sand, opens to a public that had never had an ocean beach like it.',
    },
    {
      n: 2, from: 1930, to: 1937, title: 'The city comes to him',
      text: 'Fiorello La Guardia takes office in January 1934 and hands Moses every park job in the city at once, plus a seat on the new Triborough Bridge Authority. With federal relief labor he rebuilds the Central Park Zoo in a year, opens eleven giant pools in one summer, and on 11 July 1936 opens the Triborough Bridge. The same year he loses the only election he ever ran, for governor, in a landslide, and never faces voters again.',
    },
    {
      n: 3, from: 1937, to: 1946, title: 'An authority of his own',
      text: 'Triborough tolls pour in, and the bond contracts that secure them put the authority beyond the reach of any mayor or governor for as long as the bonds run. Moses learns to roll one toll project into the next rather than retire the debt: Marine Parkway, the Whitestone, the Belt Parkway ringing Brooklyn and Queens. The 1939 World’s Fair turns a Queens ash dump into Flushing Meadows. When he tries to throw a bridge across the harbor at the Battery, only a president can stop him.',
    },
    {
      n: 4, from: 1946, to: 1956, title: 'Coordinator of everything',
      text: 'Postwar mayors make him City Construction Coordinator, then chairman of the committee that spends federal Title I slum-clearance money. He helps land the United Nations, brokers Stuyvesant Town, and drives the Cross Bronx Expressway through a living neighborhood, rejecting a route one block south that would have spared East Tremont. In 1954 Governor Dewey adds the State Power Authority, and the Niagara and St. Lawrence rivers to his portfolio.',
    },
    {
      n: 5, from: 1956, to: 1962, title: 'The tide turns',
      text: 'The first defeats are small and local. Mothers in Greenwich Village stop a road through Washington Square in 1958. Reporters expose how Title I sponsors profited from cleared land, and in 1960 Moses gives up his city posts to run the coming World’s Fair. The great projects still open on schedule: the Coliseum, the St. Lawrence and Niagara power plants, the Throgs Neck Bridge, and, on the rubble of San Juan Hill, Lincoln Center.',
    },
    {
      n: 6, from: 1962, to: 1969, title: 'The last bridge',
      text: 'Jane Jacobs’s Death and Life of Great American Cities is published in 1961, and the Lower Manhattan Expressway becomes the fight that names an era. The Verrazzano-Narrows opens in November 1964, the longest suspension span in the world; the 1964 Fair loses money. In 1968 Nelson Rockefeller folds Triborough into a new Metropolitan Transportation Authority so its tolls can subsidize the subways. Moses is promised a role that never materializes. Forty-four years of appointed power end without a vote.',
    },
  ],

  events: [
    // ---------------- Chapter 1: 1924–1929 ----------------
    {
      id: 'lispc-1924', t: 1924.3, date: 'April 1924', type: 'office',
      title: 'Long Island State Park Commission created',
      lat: 40.73, lon: -73.34, zoom: 9,
      body: 'Al Smith signs the law creating the commission and names Moses its president. Moses drafted the act himself, including the power to appropriate land before paying for it. Headquarters: Belmont Lake State Park in North Babylon, from which the Long Island system was run for four decades.',
      src: 'https://en.wikipedia.org/wiki/Long_Island_State_Park_Commission', srcName: 'Wikipedia: Long Island State Park Commission',
    },
    {
      id: 'secretary-1927', t: 1927.05, date: '1927', type: 'office',
      title: 'New York Secretary of State',
      lat: 42.6526, lon: -73.7562, zoom: 7,
      body: 'Smith appoints Moses Secretary of State of New York, a post he holds until Smith leaves Albany at the end of 1928. It is the closest Moses ever comes to statewide elected power, and it lets him keep drafting the laws his own commissions run under.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'southern-state-1927', t: 1927.6, date: '1927 (first section)', type: 'parkway',
      title: 'Southern State Parkway',
      lat: 40.6845, lon: -73.60, zoom: 10, route: 'Southern State Parkway',
      body: 'Construction began in 1925 and the first section opened in 1927, the spine of the Long Island park system. It reached Bay Shore Road in 1949 and its present end at the Sagtikos in 1962. Its low stone bridges are the subject of the most argued-over claim in Caro’s book (see the 1929 card on the parkway bridges).',
      src: 'https://en.wikipedia.org/wiki/Southern_State_Parkway', srcName: 'Wikipedia: Southern State Parkway',
    },
    {
      id: 'heckscher-1929', t: 1929.4, date: '1929', type: 'park',
      title: 'Heckscher State Park (the Taylor estate)',
      lat: 40.70, lon: -73.16, zoom: 10,
      body: 'The 1,600-acre Taylor estate at East Islip was the commission’s first great land fight: Moses seized it by appropriation, the estate’s wealthy neighbors sued, and the case went to the state’s highest court. Philanthropist August Heckscher’s gift covered the purchase and the park carries his name.',
      src: 'https://en.wikipedia.org/wiki/Heckscher_State_Park', srcName: 'Wikipedia: Heckscher State Park',
    },
    {
      id: 'wantagh-1929', t: 1929.5, date: '1929', type: 'parkway',
      title: 'Wantagh State Parkway (Jones Beach Causeway)',
      lat: 40.64, lon: -73.51, zoom: 10, route: 'Wantagh State Parkway',
      body: 'Begun in 1927, the first five miles opened in 1929 as the Jones Beach Causeway, carrying cars from Merrick Road across the bay to the new beach. Later extended north to the Northern State Parkway.',
      src: 'https://en.wikipedia.org/wiki/Wantagh_State_Parkway', srcName: 'Wikipedia: Wantagh State Parkway',
    },
    {
      id: 'jones-beach-1929', t: 1929.6, date: '4 August 1929', type: 'park',
      title: 'Jones Beach State Park opens',
      lat: 40.5958, lon: -73.5153, zoom: 10,
      body: 'Dredges pumped sand from what is now the State Boat Channel to raise a string of barrier islands fourteen feet and join them into one 6.5-mile beach. Bathhouses, a water tower styled as a campanile, and a two-mile boardwalk followed. It remains the most visited beach on the East Coast, at roughly six million visitors a year.',
      src: 'https://en.wikipedia.org/wiki/Jones_Beach_State_Park', srcName: 'Wikipedia: Jones Beach State Park',
    },
    {
      id: 'bridges-claim-1929', t: 1929.9, date: '1920s–30s (a disputed claim)', type: 'cost',
      title: 'The parkway bridges: Caro’s claim and the dispute',
      lat: 40.6746, lon: -73.6960, zoom: 11,
      body: 'Caro, citing Moses’s long-time aide Sidney Shapiro, wrote that Moses had the parkway overpasses built low so that buses, and the poor and Black New Yorkers who rode them, could not reach Jones Beach. Sociologist Bernward Joerges (1999) and historian Kenneth T. Jackson call the story an urban legend, noting that buses were kept off parkways by rule anyway. In 2017 Thomas Campanella measured twenty Southern State bridges and found them substantially lower than on comparable parkways. The bridges are real; the intent is contested.',
      src: 'https://www.historynewsnetwork.org/article/fact-check-history-of-robert-mosess-parkways-shows', srcName: 'History News Network fact check (2021)',
      src2: 'https://en.wikipedia.org/wiki/Robert_Moses#Criticism', src2Name: 'Wikipedia: Robert Moses — criticism',
    },

    // ---------------- Chapter 2: 1930–1936 ----------------
    {
      id: 'northern-state-1933', t: 1933.55, date: '15 July 1933 (first section)', type: 'parkway',
      title: 'Northern State Parkway',
      lat: 40.77, lon: -73.53, zoom: 10, route: 'Northern State Parkway',
      body: 'The north-shore sister of the Southern State, opened in stages from 1933 to 1965. Its route bends south around the Gold Coast estates; Caro’s account of that bend, and of a $10,000 payment to keep the road off Otto Kahn’s golf course, is one of the book’s set pieces.',
      src: 'https://en.wikipedia.org/wiki/Northern_State_Parkway', srcName: 'Wikipedia: Northern State Parkway',
    },
    {
      id: 'gcp-1933', t: 1933.6, date: '1933 (first section)', type: 'parkway',
      title: 'Grand Central Parkway',
      lat: 40.74, lon: -73.80, zoom: 11, route: 'Grand Central Parkway',
      body: 'The Queens link between the city and the Long Island parkways, later carried west to the Triborough Bridge. Fourteen and a half miles from the East River to the Nassau line, past what would become Flushing Meadows and LaGuardia Airport.',
      src: 'https://en.wikipedia.org/wiki/Grand_Central_Parkway', srcName: 'Wikipedia: Grand Central Parkway',
    },
    {
      id: 'parks-commissioner-1934', t: 1934.05, date: 'January 1934', type: 'office',
      title: 'City Parks Commissioner',
      lat: 40.7677, lon: -73.9713, zoom: 13,
      body: 'La Guardia merges the five borough park departments into one and gives it to Moses, who keeps his state jobs. From the Arsenal in Central Park he runs a system that will grow by 658 playgrounds, 416 miles of parkway and 13 bridges before he leaves in 1960.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'tba-1934', t: 1934.15, date: 'February 1934', type: 'office',
      title: 'Joins the Triborough Bridge Authority',
      lat: 40.7875, lon: -73.9253, zoom: 12,
      body: 'Created by the state in 1933 to finish a bridge the city had started and abandoned, the authority could sell bonds and keep the tolls. Moses joins in February 1934 and becomes chairman in November 1936. Its headquarters sits under the bridge on Randall’s Island; from here he would run the rest of his career.',
      src: 'https://en.wikipedia.org/wiki/Triborough_Bridge_and_Tunnel_Authority', srcName: 'Wikipedia: Triborough Bridge and Tunnel Authority',
    },
    {
      id: 'bethpage-1934', t: 1934.4, date: '1934–36', type: 'park',
      title: 'Bethpage State Park',
      lat: 40.7525, lon: -73.4675, zoom: 10,
      body: 'A former private estate and golf club turned into a public golf park under a Bethpage authority Moses also headed. The Black Course, opened in 1936, later hosted the U.S. Open and the Ryder Cup.',
      src: 'https://en.wikipedia.org/wiki/Bethpage_State_Park', srcName: 'Wikipedia: Bethpage State Park',
    },
    {
      id: 'governor-1934', t: 1934.85, date: 'November 1934', type: 'office',
      title: 'Runs for governor, loses in a landslide',
      lat: 42.6526, lon: -73.7562, zoom: 7,
      body: 'The Republican nominee against Herbert Lehman, Moses campaigned with contempt for the voters and lost by the largest margin in the state’s history to that point. He never ran for anything again; every job after this was appointed.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'zoo-1934', t: 1934.92, date: '2 December 1934', type: 'park',
      title: 'Central Park Zoo rebuilt',
      lat: 40.7678, lon: -73.9717, zoom: 14,
      body: 'The Victorian menagerie was torn down and replaced within Moses’s first year, built with Civil Works Administration and WPA labor. It became the emblem of the 1934 park revival: fast, federal money, and no hearings.',
      src: 'https://en.wikipedia.org/wiki/Central_Park_Zoo', srcName: 'Wikipedia: Central Park Zoo',
    },
    {
      id: 'meadowbrook-1934', t: 1934.75, date: '1933–35', type: 'parkway',
      title: 'Meadowbrook causeway',
      lat: 40.62, lon: -73.56, zoom: 10, route: 'Meadowbrook State Parkway',
      body: 'A second causeway to Jones Beach, begun in July 1933 with a Reconstruction Finance Corporation loan, so that the beach could be reached from the west as well as from Wantagh.',
      src: 'https://en.wikipedia.org/wiki/Meadowbrook_State_Parkway', srcName: 'Wikipedia: Meadowbrook State Parkway',
    },
    {
      id: 'pools-1936', t: 1936.5, date: 'Summer 1936', type: 'park',
      title: 'Eleven WPA pools in one summer',
      lat: 40.7794, lon: -73.9219, zoom: 12,
      body: 'Between June and August 1936 the Parks Department opened eleven enormous outdoor pools, one roughly every week, with combined room for about 49,000 swimmers. Astoria Pool, shown here, hosted the Olympic swimming trials that August; McCarren in Brooklyn and Hamilton Fish on the Lower East Side are others still standing.',
      src: 'https://en.wikipedia.org/wiki/Astoria_Park', srcName: 'Wikipedia: Astoria Park',
    },
    {
      id: 'triborough-1936', t: 1936.53, date: '11 July 1936', type: 'bridge',
      title: 'Triborough Bridge opens',
      lat: 40.7875, lon: -73.9253, zoom: 12,
      body: 'Three bridges and miles of viaduct tying Manhattan, Queens and the Bronx together across Randall’s and Ward’s islands, opened by President Roosevelt. The tolls ran to tens of millions of dollars a year, and instead of paying off the bonds Moses used the surplus to build the next toll crossing, then the next. This is the financial engine of everything that follows.',
      src: 'https://en.wikipedia.org/wiki/Robert_F._Kennedy_Bridge', srcName: 'Wikipedia: Robert F. Kennedy (Triborough) Bridge',
    },
    {
      id: 'orchard-beach-1936', t: 1936.6, date: '1936–37', type: 'park',
      title: 'Orchard Beach',
      lat: 40.8673, lon: -73.7925, zoom: 12,
      body: 'The Bronx’s only public beach, made by filling in the water between islands in Pelham Bay Park and importing sand. Dedicated in 1936, opened with its pavilion in 1937.',
      src: 'https://en.wikipedia.org/wiki/Orchard_Beach,_Bronx', srcName: 'Wikipedia: Orchard Beach',
    },
    {
      id: 'henry-hudson-1936', t: 1936.95, date: '1934–37', type: 'parkway',
      title: 'Henry Hudson Parkway and Bridge',
      lat: 40.8779, lon: -73.9218, zoom: 12, route: 'Henry Hudson Parkway',
      body: 'Eleven miles up the Hudson from 72nd Street to the Westchester line, built by a Henry Hudson Parkway Authority Moses controlled. The bridge over Spuyten Duyvil opened in December 1936 through Inwood Hill Park; Riverside Park was rebuilt over the railroad to carry the road south.',
      src: 'https://en.wikipedia.org/wiki/Henry_Hudson_Parkway', srcName: 'Wikipedia: Henry Hudson Parkway',
    },

    // ---------------- Chapter 3: 1937–1945 ----------------
    {
      id: 'marine-parkway-1937', t: 1937.5, date: '3 July 1937', type: 'bridge',
      title: 'Marine Parkway Bridge and Jacob Riis Park',
      lat: 40.5734, lon: -73.8849, zoom: 12,
      body: 'A vertical-lift bridge over Rockaway Inlet, built by a Marine Parkway Authority, joining Brooklyn to the Rockaways and to Riis Park, which Moses rebuilt in 1936–37 as a city Jones Beach.',
      src: 'https://en.wikipedia.org/wiki/Marine_Parkway%E2%80%93Gil_Hodges_Memorial_Bridge', srcName: 'Wikipedia: Marine Parkway Bridge',
    },
    {
      id: 'whitestone-1939', t: 1939.33, date: '29 April 1939', type: 'bridge',
      title: 'Bronx–Whitestone Bridge',
      lat: 40.8011, lon: -73.8292, zoom: 12,
      body: 'Othmar Ammann’s slender suspension bridge, approved in 1936 and finished in time for the World’s Fair, built by Triborough on Triborough bonds. Its deck was so like the Tacoma Narrows that stiffening trusses were added after that bridge fell in 1940.',
      src: 'https://en.wikipedia.org/wiki/Bronx%E2%80%93Whitestone_Bridge', srcName: 'Wikipedia: Bronx–Whitestone Bridge',
    },
    {
      id: 'worlds-fair-1939', t: 1939.33, date: '30 April 1939', type: 'culture',
      title: '1939 World’s Fair, Flushing Meadows',
      lat: 40.7458, lon: -73.8447, zoom: 12,
      body: 'Moses agreed to host the fair on the Corona ash dump on condition that the site be left to him as a park. The fair drew more than 45 million visitors over two seasons and lost money; the park, the Grand Central Parkway and the Whitestone approaches stayed.',
      src: 'https://en.wikipedia.org/wiki/1939_New_York_World%27s_Fair', srcName: 'Wikipedia: 1939 New York World’s Fair',
    },
    {
      id: 'battery-bridge-1939', t: 1939.55, date: '1939', type: 'cost',
      title: 'The Brooklyn–Battery Bridge is stopped',
      lat: 40.7035, lon: -74.0168, zoom: 13,
      body: 'Moses wanted a bridge, not a tunnel, from the Battery to Brooklyn, one that would have walled off the tip of Manhattan. Reform groups and the Regional Plan Association objected, and the War Department refused approval on the grounds that a bridge could block the Navy Yard; Caro has Roosevelt, an old enemy, arranging the refusal. The tunnel was built instead.',
      src: 'https://en.wikipedia.org/wiki/Hugh_L._Carey_Tunnel', srcName: 'Wikipedia: Brooklyn–Battery Tunnel',
    },
    {
      id: 'belt-parkway-1940', t: 1940.5, date: '29 June 1940', type: 'parkway',
      title: 'Belt Parkway',
      lat: 40.60, lon: -73.95, zoom: 11, route: 'Belt Parkway',
      body: 'A ring of parkways around the shore of Brooklyn and Queens, opened in one day in 1940, with the Cross Island Parkway closing the loop on the east. Twenty-five miles of it are Belt Parkway proper; the Shore, Southern and Laurelton sections are the pieces.',
      src: 'https://en.wikipedia.org/wiki/Belt_Parkway', srcName: 'Wikipedia: Belt Parkway',
    },
    {
      id: 'gowanus-1941', t: 1941.8, date: '1941', type: 'expressway',
      title: 'Gowanus Parkway over Third Avenue',
      lat: 40.655, lon: -74.005, zoom: 13, route: 'Gowanus Expressway',
      body: 'An elevated road carried down the middle of Third Avenue in Sunset Park on the old BMT el structure, rather than one block west over the rail yards. Caro’s chapter on it, “One Mile,” treats it as the moment Moses first took a road through a neighborhood rather than around it.',
      src: 'https://en.wikipedia.org/wiki/Gowanus_Expressway', srcName: 'Wikipedia: Gowanus Expressway',
    },
    {
      id: 'castle-clinton-1941', t: 1941.7, date: '1941–46', type: 'cost',
      title: 'Castle Clinton nearly demolished',
      lat: 40.7035, lon: -74.0168, zoom: 14,
      body: 'With the aquarium closed in 1941, Moses set out to level the 1811 fort at the Battery for the tunnel approaches and a new park. Preservationists held him off for five years until Congress made it a national monument in 1946. One of the few old buildings that beat him.',
      src: 'https://en.wikipedia.org/wiki/Castle_Clinton', srcName: 'Wikipedia: Castle Clinton',
    },
    {
      id: 'planning-1942', t: 1942.1, date: '1942', type: 'office',
      title: 'Seat on the City Planning Commission',
      lat: 40.7128, lon: -74.0060, zoom: 13,
      body: 'La Guardia adds Moses to the commission that was supposed to check him. He keeps the seat until 1960, which means the body reviewing his highway and housing plans includes their author.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },

    // ---------------- Chapter 4: 1946–1955 ----------------
    {
      id: 'coordinator-1946', t: 1946.1, date: '1946', type: 'office',
      title: 'City Construction Coordinator',
      lat: 40.7128, lon: -74.0060, zoom: 13,
      body: 'Mayor O’Dwyer creates the post for him: every public work in the city, including housing, now passes across his desk. The same year the state merges the Tunnel Authority into Triborough, giving him the Queens-Midtown and the Battery tunnels and their tolls.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'un-1946', t: 1946.95, date: 'December 1946', type: 'culture',
      title: 'United Nations headquarters site',
      lat: 40.7494, lon: -73.9681, zoom: 13,
      body: 'When the UN was about to leave New York for Philadelphia, Moses and the city’s site committee steered it to William Zeckendorf’s slaughterhouse parcel on the East River, bought with John D. Rockefeller Jr.’s gift and handed over in December 1946. The complex was finished in 1952.',
      src: 'https://en.wikipedia.org/wiki/Headquarters_of_the_United_Nations', srcName: 'Wikipedia: Headquarters of the United Nations',
    },
    {
      id: 'stuytown-1947', t: 1947.6, date: '1947 (first buildings)', type: 'housing',
      title: 'Stuyvesant Town',
      lat: 40.732, lon: -73.978, zoom: 13,
      body: 'Moses brokered the 1943 deal under which Metropolitan Life cleared the eighteen blocks of the Gas House District and built 110 brick towers with a tax break and the city’s condemnation power. It opened in 1947 to white tenants only, a policy the city had accepted and that took years of litigation and protest to end.',
      src: 'https://en.wikipedia.org/wiki/Stuyvesant_Town%E2%80%93Peter_Cooper_Village', srcName: 'Wikipedia: Stuyvesant Town–Peter Cooper Village',
    },
    {
      id: 'cross-bronx-1948', t: 1948.5, date: '1948 (construction begins)', type: 'expressway',
      title: 'Cross Bronx Expressway begun',
      lat: 40.8455, lon: -73.9095, zoom: 12, route: 'Cross Bronx Expressway',
      body: 'The first highway pushed through a dense American city, built from 1948 to 1972 at a final cost of $128 million; one mile of it, tunnelled under the Grand Concourse and the subway, was the most expensive mile of road ever built. The eastern sections opened first, in 1950 and 1955; the Alexander Hamilton Bridge closed the last gap in 1963.',
      src: 'https://en.wikipedia.org/wiki/Cross_Bronx_Expressway', srcName: 'Wikipedia: Cross Bronx Expressway',
    },
    {
      id: 'slum-clearance-1949', t: 1949.6, date: '1949', type: 'office',
      title: 'Chairman, Committee on Slum Clearance',
      lat: 40.7128, lon: -74.0060, zoom: 13,
      body: 'The federal Housing Act of 1949 pays two-thirds of the cost of clearing a “slum” and selling the land to a private builder. Moses chairs the mayor’s committee that picks the sites and the builders. In the seven years after the war about 170,000 New Yorkers were moved out of their homes for public projects, most of them his.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'battery-tunnel-1950', t: 1950.4, date: '25 May 1950', type: 'bridge',
      title: 'Brooklyn–Battery Tunnel',
      lat: 40.6970, lon: -74.0145, zoom: 13,
      body: 'The tunnel he had fought, finished under his own Triborough after the 1946 merger. At 9,117 feet it is still the longest continuous underwater road tunnel in North America, and its tolls joined the Triborough surplus.',
      src: 'https://en.wikipedia.org/wiki/Hugh_L._Carey_Tunnel', srcName: 'Wikipedia: Brooklyn–Battery Tunnel',
    },
    {
      id: 'bqe-promenade-1950', t: 1950.8, date: '1950', type: 'expressway',
      title: 'Brooklyn–Queens Expressway and the Heights Promenade',
      lat: 40.6975, lon: -73.9973, zoom: 13, route: 'Brooklyn-Queens Expressway',
      body: 'Moses wanted the expressway straight through Brooklyn Heights. The neighborhood won a rare compromise: the road was stacked into two cantilevered decks against the bluff with a public promenade on top, opened in 1950. Elsewhere along its route, in Williamsburg and Red Hook, there was no promenade.',
      src: 'https://en.wikipedia.org/wiki/Brooklyn_Heights_Promenade', srcName: 'Wikipedia: Brooklyn Heights Promenade',
    },
    {
      id: 'van-wyck-1950', t: 1950.9, date: '1950–53', type: 'expressway',
      title: 'Van Wyck Expressway to Idlewild',
      lat: 40.70, lon: -73.81, zoom: 12, route: 'Van Wyck Expressway',
      body: 'Opened in pieces between 1950 and 1953 to carry traffic from the Grand Central Parkway to the new Idlewild (now JFK) airport. Caro faults it for being built with no provision for a rail line in its median, at a time when one would have been cheap.',
      src: 'https://en.wikipedia.org/wiki/Interstate_678', srcName: 'Wikipedia: Interstate 678 (Van Wyck Expressway)',
    },
    {
      id: 'east-tremont-1953', t: 1953.35, date: 'April–May 1953', type: 'cost',
      title: 'East Tremont: the route one block south',
      lat: 40.8455, lon: -73.8920, zoom: 13,
      body: 'Residents of East Tremont, backed by Bronx Borough President James Lyons, proposed shifting the central section along the edge of Crotona Park, sparing roughly a thousand homes. Moses refused, threatened to walk away with the federal money, and the Board of Estimate approved his line in May 1953. About 1,462 families were moved for the central section alone; Caro’s chapter on it is the moral center of The Power Broker.',
      src: 'https://en.wikipedia.org/wiki/Cross_Bronx_Expressway', srcName: 'Wikipedia: Cross Bronx Expressway',
    },
    {
      id: 'power-authority-1954', t: 1954.4, date: '1954', type: 'office',
      title: 'Chairman, State Power Authority',
      lat: 43.1431, lon: -79.0397, zoom: 7,
      body: 'Governor Dewey gives Moses the authority that will harness the St. Lawrence and Niagara rivers. He now holds a dozen state and city posts at once, none of them elected, and can pay for the power projects the same way he paid for bridges: with bonds secured on the revenue.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
    },
    {
      id: 'lincoln-square-1955', t: 1955.3, date: '21 April 1955', type: 'housing',
      title: 'Lincoln Square designated for renewal',
      lat: 40.7725, lon: -73.9839, zoom: 13,
      body: 'The Board of Estimate approves the Slum Clearance Committee’s Lincoln Square plan: the working-class blocks of San Juan Hill are condemned under Title I for a performing-arts center, Fordham’s campus and middle-income towers. More than 7,000 residents and 800 businesses were displaced.',
      src: 'https://en.wikipedia.org/wiki/Lincoln_Center', srcName: 'Wikipedia: Lincoln Center',
    },

    // ---------------- Chapter 5: 1956–1961 ----------------
    {
      id: 'coliseum-1956', t: 1956.32, date: '28 April 1956', type: 'culture',
      title: 'New York Coliseum, Columbus Circle',
      lat: 40.7681, lon: -73.9819, zoom: 14,
      body: 'A convention hall and office tower built by Triborough itself on a Title I site at Columbus Circle, a demonstration that the authority could build anything, not only bridges. Demolished in 2000 for the Time Warner Center.',
      src: 'https://en.wikipedia.org/wiki/New_York_Coliseum', srcName: 'Wikipedia: New York Coliseum',
    },
    {
      id: 'dodgers-1957', t: 1957.75, date: '1957', type: 'cost',
      title: 'The Dodgers leave Brooklyn',
      lat: 40.6842, lon: -73.9760, zoom: 13,
      body: 'Walter O’Malley wanted the city to condemn land at Atlantic and Flatbush avenues for a new ballpark. Moses refused to use Title I for a private stadium and offered Flushing Meadows instead; O’Malley took the team to Los Angeles after the 1957 season. The Flushing site became Shea Stadium.',
      src: 'https://en.wikipedia.org/wiki/Shea_Stadium', srcName: 'Wikipedia: Shea Stadium',
    },
    {
      id: 'washington-square-1958', t: 1958.6, date: '1958 (permanent 1959)', type: 'cost',
      title: 'Washington Square closed to cars',
      lat: 40.7308, lon: -73.9975, zoom: 14,
      body: 'Moses had planned since 1952 to carry Fifth Avenue through the park and on into an urban-renewal district south of it. Shirley Hayes’s Washington Square Park Committee, joined by Jane Jacobs and Eleanor Roosevelt, demanded the park be closed to traffic altogether. A 1958 trial closure was made permanent in 1959: the first clear defeat of a Moses road in Manhattan.',
      src: 'https://en.wikipedia.org/wiki/Washington_Square_Park', srcName: 'Wikipedia: Washington Square Park',
    },
    {
      id: 'st-lawrence-1958', t: 1958.6, date: '1958', type: 'power',
      title: 'St. Lawrence power project, Massena',
      lat: 44.9836, lon: -74.7963, zoom: 8,
      body: 'The Moses–Saunders dam across the St. Lawrence at Massena, built jointly with Ontario Hydro, began generating in 1958 as part of the Seaway. Villages on both sides of the river were drowned behind it; Moses’s name is on the American half.',
      src: 'https://en.wikipedia.org/wiki/Moses%E2%80%93Saunders_Power_Dam', srcName: 'Wikipedia: Moses–Saunders Power Dam',
    },
    {
      id: 'title-one-1959', t: 1959.4, date: '1959', type: 'cost',
      title: 'The Title I scandals',
      lat: 40.7936, lon: -73.9680, zoom: 13,
      body: 'Newspaper investigations in 1959 showed that politically connected sponsors of slum-clearance sites had collected rents from tenants for years without building, and that the committee had done little to check them. Manhattantown on the Upper West Side, shown here, was the notorious case. Moses gave up the committee, and his city posts, in 1960.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses', srcName: 'Wikipedia: Robert Moses',
      src2: 'https://en.wikipedia.org/wiki/The_Power_Broker', src2Name: 'Wikipedia: The Power Broker',
    },
    {
      id: 'lincoln-center-1959', t: 1959.37, date: '14 May 1959', type: 'culture',
      title: 'Lincoln Center groundbreaking',
      lat: 40.7725, lon: -73.9839, zoom: 14,
      body: 'President Eisenhower turns the first shovel. Philharmonic Hall opened in September 1962, the Metropolitan Opera House in 1966. The complex is the best-loved thing Title I built and the clearest record of what it cost.',
      src: 'https://en.wikipedia.org/wiki/Lincoln_Center', srcName: 'Wikipedia: Lincoln Center',
    },
    {
      id: 'fair-corp-1960', t: 1960.4, date: 'May 1960', type: 'office',
      title: 'Leaves the city to run the World’s Fair',
      lat: 40.7458, lon: -73.8447, zoom: 12,
      body: 'Moses resigns as Parks Commissioner, Construction Coordinator and planning commissioner to become president of the 1964 World’s Fair Corporation, at a salary. He keeps Triborough and the Power Authority.',
      src: 'https://en.wikipedia.org/wiki/1964_New_York_World%27s_Fair', srcName: 'Wikipedia: 1964 New York World’s Fair',
    },
    {
      id: 'throgs-neck-1961', t: 1961.03, date: '11 January 1961', type: 'bridge',
      title: 'Throgs Neck Bridge',
      lat: 40.802, lon: -73.793, zoom: 12,
      body: 'A second East River suspension bridge two miles east of the Whitestone, built by Triborough to relieve it. The newest bridge across the East River.',
      src: 'https://en.wikipedia.org/wiki/Throgs_Neck_Bridge', srcName: 'Wikipedia: Throgs Neck Bridge',
    },
    {
      id: 'niagara-1961', t: 1961.1, date: '1961', type: 'power',
      title: 'Niagara Power Project, Lewiston',
      lat: 43.1431, lon: -79.0397, zoom: 8,
      body: 'After the private Schoellkopf plant collapsed into the gorge in 1956, the Power Authority built the plant that replaced it in under four years. Today the Robert Moses Niagara plant is rated at about 2,500 megawatts, the largest hydroelectric station in the state.',
      src: 'https://en.wikipedia.org/wiki/Robert_Moses_Niagara_Power_Plant', srcName: 'Wikipedia: Robert Moses Niagara Power Plant',
    },

    // ---------------- Chapter 6: 1962–1968 ----------------
    {
      id: 'lomex-1962', t: 1962.9, date: '1962 (blocked)', type: 'unbuilt',
      title: 'Lower Manhattan Expressway',
      lat: 40.7215, lon: -73.9990, zoom: 13,
      body: 'Conceived in 1941: a ten-lane elevated road from the Holland Tunnel across SoHo and Little Italy to the Williamsburg and Manhattan bridges, displacing about 2,000 families and 800 or more businesses. Approved in 1960, blocked by the Board of Estimate in December 1962 after Jane Jacobs organized the opposition, revived and finally cancelled by Mayor Lindsay in 1969 and struck from the state map in 1971.',
      src: 'https://en.wikipedia.org/wiki/Lower_Manhattan_Expressway', srcName: 'Wikipedia: Lower Manhattan Expressway',
    },
    {
      id: 'cross-bronx-1963', t: 1963.4, date: 'May 1963', type: 'expressway',
      title: 'Cross Bronx completed to the Hamilton Bridge',
      lat: 40.8455, lon: -73.9260, zoom: 12,
      body: 'The Alexander Hamilton Bridge over the Harlem River links the expressway to the George Washington Bridge, and fifteen years of work through the Bronx is joined end to end. The neighborhoods it cut through, East Tremont among them, emptied over the following decade.',
      src: 'https://en.wikipedia.org/wiki/Cross_Bronx_Expressway', srcName: 'Wikipedia: Cross Bronx Expressway',
    },
    {
      id: 'shea-1964', t: 1964.3, date: '17 April 1964', type: 'culture',
      title: 'Shea Stadium',
      lat: 40.7556, lon: -73.8481, zoom: 13,
      body: 'The Flushing Meadows ballpark Moses had offered the Dodgers, built for the expansion Mets and opened a week before the Fair next door.',
      src: 'https://en.wikipedia.org/wiki/Shea_Stadium', srcName: 'Wikipedia: Shea Stadium',
    },
    {
      id: 'worlds-fair-1964', t: 1964.31, date: '22 April 1964', type: 'culture',
      title: '1964 World’s Fair',
      lat: 40.7458, lon: -73.8447, zoom: 12,
      body: 'Two six-month seasons under the Unisphere, without the sanction of the Bureau International des Expositions, which Moses had refused to court; most of Europe stayed away. Projected at 70 million visitors, it drew 51.6 million and lost money. It was the last thing he ran.',
      src: 'https://en.wikipedia.org/wiki/1964_New_York_World%27s_Fair', srcName: 'Wikipedia: 1964 New York World’s Fair',
    },
    {
      id: 'fire-island-1964', t: 1964.7, date: '11 September 1964', type: 'unbuilt',
      title: 'The Fire Island road that was not built',
      lat: 40.6964, lon: -72.9828, zoom: 9,
      body: 'Moses wanted a four-lane parkway down the length of Fire Island, an Ocean Parkway for Suffolk. Islanders lobbied Washington instead, and Congress created Fire Island National Seashore in September 1964, leaving the island with no through road. The state park at its western tip was renamed for him.',
      src: 'https://en.wikipedia.org/wiki/Fire_Island_National_Seashore', srcName: 'Wikipedia: Fire Island National Seashore',
    },
    {
      id: 'verrazzano-1964', t: 1964.89, date: '21 November 1964', type: 'bridge',
      title: 'Verrazzano-Narrows Bridge',
      lat: 40.6064, lon: -74.0456, zoom: 12,
      body: 'Ammann’s last great span and the longest suspension bridge in the world when it opened, joining Staten Island to the city at last. The Bay Ridge approach, approved in December 1958, displaced about 7,500 people. The lower deck opened in 1969.',
      src: 'https://en.wikipedia.org/wiki/Verrazzano-Narrows_Bridge', srcName: 'Wikipedia: Verrazzano-Narrows Bridge',
    },
    {
      id: 'northern-state-1965', t: 1965.45, date: '9 June 1965', type: 'parkway',
      title: 'Northern State reaches Hauppauge',
      lat: 40.83, lon: -73.22, zoom: 10,
      body: 'The final extension to Veterans Memorial Highway, thirty-two years after the first section. Its 28.9 miles, and the Southern State’s 25.5, are the frame of the Long Island system begun in 1924.',
      src: 'https://en.wikipedia.org/wiki/Northern_State_Parkway', srcName: 'Wikipedia: Northern State Parkway',
    },
    {
      id: 'mta-1968', t: 1968.17, date: '1 March 1968', type: 'office',
      title: 'Triborough folded into the MTA',
      lat: 40.7875, lon: -73.9253, zoom: 12,
      body: 'Governor Rockefeller’s Metropolitan Transportation Authority absorbs Triborough so that bridge and tunnel tolls can subsidize the subways and commuter railroads. Moses, who had fought the merger, is told he will have a role; it never comes. He is 79. The tolls have since sent more than $10 billion to transit.',
      src: 'https://en.wikipedia.org/wiki/Triborough_Bridge_and_Tunnel_Authority', srcName: 'Wikipedia: Triborough Bridge and Tunnel Authority',
    },
  ],
};
